### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by miriamposner** [digitalinteraction/past-paths#1]
Hi! I'd love to see this project in action, but the link to the Tyne & Wales interface appears to be broken. ("Internal error occurred.") Thank you!

**Comment by garbit** [comment]
Hi Miriam, we're working to resolve this issue in the next week or so. I'll make sure to post here once we've resolved the issue so you can take a look.

**Comment by garbit** [comment]
Hi Miriam, we've now got the project back up and running.

Feel free to take a look at the project in action here: [http://collectionsdivetwmuseums.org.uk/](http://collectionsdivetwmuseums.org.uk/)
